name: Frontend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  terraform-apply:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: 'frontend'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.4.0
      
      - name: Terraform Init
        id: init
        run: cd frontend && terraform init
        working-directory: ./frontend

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: cd frontend && terraform apply -auto-approve -input=false
        working-directory: ./frontend